# Generated by Django 4.0.6 on 2022-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ousermodel',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
